export const T = {
  GET_FOOTER_ACTIVE_TAB: "GET_FOOTER_ACTIVE_TAB",
  CHANGE_FOOTER_ACTIVE_TAB: "CHANGE_FOOTER_ACTIVE_TAB",
  CHANGE_WEIGHT_PALETTE_SHOW_STATE: "CHANGE_WEIGHT_PALETTE_SHOW_STATE",
  CHANGE_PALETTE_SHOW_STATE: "CHANGE_PALETTE_SHOW_STATE",
  CHANGE_PALETTE_COLOR: "CHANGE_PALETTE_COLOR",
  CHANGE_TEXT_UPDATE_MENU_ACTIVE_TAB: "CHANGE_TEXT_UPDATE_MENU_ACTIVE_TAB",
  LOCAL_STORAGE_CLIPED_IMAGES: "LOCAL_STORAGE_CLIPED_IMAGES",
  LOCAL_STORAGE_MAKER_IMAGES: "LOCAL_STORAGE_MAKER_IMAGES",
  CHANGE_WEIGHT_PALETTE_COLOR: "CHANGE_WEIGHT_PALETTE_COLOR",
  CHANGE_TEXT_PEN_WEIGHT_SLIDER_VALUE: "CHANGE_TEXT_PEN_WEIGHT_SLIDER_VALUE",
  CHANGE_UPDATE_WEIGHT_PALETTE_SHOW_STATE:
    "CHANGE_UPDATE_WEIGHT_PALETTE_SHOW_STATE",
  CHANGE_UPDATE_WEIGHT_PALETTE_COLOR: "CHANGE_UPDATE_WEIGHT_PALETTE_COLOR",
  CREATE_PATTERN: "CREATE_PATTERN",
  CHANGE_SHAPE_SCALE_SLIDER_VALUE: "CHANGE_SHAPE_SCALE_SLIDER_VALUE", //スケール
  CHANGE_SHAPE_DISTANCE_SLIDER_VALUE: "CHANGE_SHAPE_DISTANCE_SLIDER_VALUE", //間隔
  CHANGE_SHAPE_ROTATE_SLIDER_VALUE: "CHANGE_SHAPE_ROTATE_SLIDER_VALUE", //アングル
  CHANGE_ALL_ROTATE_SLIDER_VALUE: "CHANGE_ALL_ROTATE_SLIDER_VALUE", //プレーンローテーション
  CHANGE_SPIN_ROTATE_SLIDER_VALUE: "CHANGE_SPIN_ROTATE_SLIDER_VALUE", //スピンローテーション
  CHANGE_REVERSE_X: "CHANGE_REVERSE_X",
  CHANGE_REVERSE_Y: "CHANGE_REVERSE_Y",
  CHANGE_REVERSE_RANDOM: "CHANGE_REVERSE_RANDOM",
  CHANGE_RANDOM_SCALE: "CHANGE_RANDOM_SCALE",
  CHANGE_RANDOM_ANGLE: "CHANGE_RANDOM_ANGLE",
  CHANGE_UPDATE_TEXT_FONT_FAMILY: "CHANGE_UPDATE_TEXT_FONT_FAMILY",
  SYNC_MAKER_CANVAS_OBJECTS: "SYNC_MAKER_CANVAS_OBJECTS",
  SET_MAKER_CANVAS_DATA: "SET_MAKER_CANVAS_DATA",
  SET_UPDATE_MAKER_IMAGE_ID: "SET_UPDATE_MAKER_IMAGE_ID",
  SET_PATTERN_DATA: "SET_PATTERN_DATA",
  ADD_CLIPED_IMAGE: "ADD_CLIPED_IMAGE",
  GET_CLIPED_IMAGES: "GET_CLIPED_IMAGES"
};
